server:
  port: 8080
  tomcat:
    max-connections: 20
    threads:
      max: 20
      min-spare: 10
    accept-count: 10

# 微信公众号对接
weixin:
  config:
    originalid: gh_9a5f9b51f4e0
    token: Gong6666!
    app-id: wxd791e178e4628317
    app-secret: c459c6bd2f7850c2e3e6416d5dde9275
    template_id: mbGHV9Xyqks0eP1U3ssifNEbeLIdqe31SfwFknlDdc4

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://mysql:3306/s-pay-mall?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat

mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml
  config-location:  classpath:/mybatis/config/mybatis-config.xml

# 支付宝支付 - 沙箱 https://opendocs.alipay.com/common/02kkv7
alipay:
  enabled: true
  app_id: 9021000159639472
  merchant_private_key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCmSOFspkpOQnKTQz8m6v5XD4rbQAoEXqopn5Ci301HLdtNS9kFs9+I8yasGMtDffGovJF6yYQ5WcTha8iCS7ey1B3GwC0Z7kxYV9Hdc2cZO825vPZ8S810hK+wZCJ1qZ6Re1wmEXEZOZ+dlduF8bgYhqYxozu3g574PBiV+XgcOJLSxqYOhMGTOgxp7qDIw2yrR3vODMj8Ng4e2XwHewCrwmyeJ02bZ3ICnlWhoU0jsDu/ozqzGLjckBhmQVGs3HAkuDVvCXaFe19E+/4zYMTzMjLkc91ZsVedSbPYS/Id4PCpxoMWB5QFhCwmbsU10WtKI6m4+T6Q4uh3g7KLjHbpAgMBAAECggEAQu+Bdqf1r00GLAtcx4C+wzLpdVpw7dNhcgHeSgHTbLyj05idkrMWX11pisssP03aUk8dzKyDwkZFf2xQuUpbduv11ISVYyPOrZ0kSJ1kuf6d0I+lNOGaobWrtziHuo992hgrPtO0kC/m9ZtWU7O6pHzHN6H6ruOXwVsHlo9mbw0biNbn4CGXaGFmu1j5bMFFMY0EHSNzT5WCjFBXVCb4sjqC2IOK0sARb5Mc8JpbxFRZbVYpTF0+PBNUN5+75cFT8F6AjgjYmqp2cAG4YBaSpQKLdyoPp4O889hEINAKvBD77gqLatzegcQz7pCKVUnq+f0u3ursZwyRxzn2IspgxQKBgQDpRwshKg8R2RR5sLT8Prk6SZyzRV4B7m94s6YClj3F8yUdEnE6RGdCskpqYHwlwPQ0XkWJbDT22BZw8Hg8KWlECQInpBNM2zsqM01ICuTnFz/OMKS1Z8/m9prx7vBOFeKoI+UyFUZzfxBrFlpd+HNbfD9RAjMB0zFfFJ3YiOH9dwKBgQC2e1GfZMBLfsofOsGi2nWevNLzhVvGeKMsM1On+kt+47UuheAZoAsejvsc84A7SCT/tSJvGb3brmy+uwsG7HbBitijtrSdtav1gO1T1HA78+dxVH3qkkr5yB7PLRSI2XI3aia+Zr/3/FG3MjawNxEvN4SZV2B1h178n2yHfYrGnwKBgQDUb9Ag2Y5zsH7G+zc2Z2CDRjofv9IGbD6zataJkIyc0fpAaWUXrOdkg7zk9wzXzMoXTqqApTvud4aoPzUfhI7KWHHP68lvuk489g8wxksCb9e5S+8TDID2Uil0nSXV1nRcrqOwYlOQJmyrOOX+oZ1b+OAoQ5pz1QInFj1QzgcPrQKBgCmuvZRFNU+JZK4Bg92pPRjHVQBfQ/lv8QXVq5RBLiGL7gT0e54e2qteSanxTSc9cYYfYAA0xxN5Iknm+7vXI8FN7/Jld5hWuTLZAl0Vt5VaP1G51RFR3WJ0/eShDYG8+cQCsVroqY0By8Cm7asOyRQaAGXueZAfHelimS3R1XNNAoGAVeyO75cNcaRVhh5NPHAYNX/zCcJ4TViQhZXMEnzAkdwJLlHry327GHzziwDRyPxoOPKwjLa91XIqnjH4dmp/tctUfrAptaMCl850RkO8ldpI12K7OS9nTq2wzD5cVXgo0sVTMSqJLnPDMK9kIR2lLlQW+Yfaxz7YNVsTYSdVarY=
  alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4QTX4O2TvHBAsdR5LNr0KgG+tIKj92wxFDHXAxULSEP3QRCu44ohrlFzog3RADotRG/sTu7N9BDJuA1+JZmbQD8RspcluERHVvml9rVynfSDYdTa5IsCscoZKu6bvym4X9iGK+yAocj7Opx6XBj9u8Zi0TF/nE9GoiQg3hG3rutiY0gXw84gpUyTM2yCd7fdEx6VfATtfjwwNIeOztsTNRX+0N6DqUN1d5GIaqdvCub+UW1JwsqLVehpMf+dCtRgMfAPnAr2WQ3W3oO3zFtA6Dshn1YYtHuIPf7F87zuCASr1lpVI8C4zmIMyA/87obR7++arT+oz2WBb/efdSk3/QIDAQAB
  notify_url: https://api.zhuodao.online/api/v1/alipay/alipay_notify_url
  return_url: https://front.zhuodao.online
  gatewayUrl: https://openapi-sandbox.dl.alipaydev.com/gateway.do

# 日志
logging:
  level:
    root: info
  config: classpath:logback-spring.xml